DROP TABLE IF EXISTS history;
CREATE TABLE history (
	id	INT AUTO_INCREMENT NOT NULL,
	date	VARCHAR(255) NOT NULL,
	fonction	VARCHAR(255) NOT NULL,
	arguments	VARCHAR(255) NOT NULL,
	sortie	VARCHAR(255) NOT NULL,
	PRIMARY KEY (`id`)
);